# Generated by Django 4.0 on 2024-03-02 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='posted_by',
        ),
    ]
