# Generated by Django 4.0 on 2024-03-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_comment_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='gayathri', max_length=100),
            preserve_default=False,
        ),
    ]
